services:
  - type: web
    name: cleansheet-backend
    env: node
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "3000"
      - key: DATABASE_URL
        value: /data/cleansheet.db
    disk:
      name: data
      mountPath: /data
      sizeGB: 1

  - type: static
    name: cleansheet-frontend
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_API_URL
        sync: false
        value: https://cleansheet-backend.onrender.com
