services:
  - type: web
    name: cleansheet-backend-prod
    env: node
    plan: free
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "3000"

  - type: web
    name: cleansheet-frontend-prod
    env: node
    plan: free
    rootDir: frontend
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: VITE_API_URL
        value: https://cleansheet-backend-prod.onrender.com
